#Este es el archivo de configuracion
server:
  port: 8081

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update    #este campo de sebe cambiar a Validate para produccion
    show-sql: true

    spring:
      application:
        name: servicio-estudiantes